### ISSUE TITLE
AMP pages

### ISSUE THREAD

**Issue by colis** [ianhampton/Tealium-Wordpress-Plugin#4]
Hi,

I implemented AMP pages and, unlike all the other active plugins, the Tealium script tag is not being stripped out on the AMP version of the page, hence the validation fails.
Any ideas?
Thank you!

**Comment by ianhampton** [comment]
Hi Colis,

That isn't entirely surprising as I'm using a non-standard method of placing the Tealium tag to fit with the Tealium guidelines of placing the tag immediately after the opening <body>.

I could make some changes to check for the AMP plugin and not insert the tag - that should be quite simple. Tealium does have a solution for tracking on AMP sites but it requires the Cloud Delivery service. I'll look into creating a proper WP implementation for this in the near future.

Thanks,
Ian

**Comment by colis** [comment]
Hi Ian and thanks for getting back to me.

I created a custom plugin to extend the default Data Object, which is where I'm enqueuing the scripts as well, so I temporarily fixed the issue simply by leaving the basic settings empty.
I thought it would've been useful for you to know about the issue anyway :)

Many thanks,
Carmine
