### ISSUE TITLE
Custom CDN

### ISSUE THREAD

**Issue by tibu** [ianhampton/Tealium-Wordpress-Plugin#6]
Hi Ian,

Would it be possible to add another field to override the custom Tealium CDN field? We're hosting the files on our own CDN.

Do you accept pull requests?

Thanks

**Comment by ianhampton** [comment]
Hi @tibu,

You can achieve this by using the 'Advanced Tag Code' field under advanced settings and pasting in your tag loading code with the updated URL.

I'll look at adding another field just to update the domain and still pull the account/profile/environment details from the basic settings.

Thanks for the suggestion!

Ian
